### ISSUE TITLE
integration  with picc.io

### ISSUE THREAD

**Issue by callagg1** [Araime/Download-upload-imgur#1]
Can we get this to integrate with [picc.io](https://picc.io) ?

**Comment by Araime** [comment]
![Новый точечный рисунок8](https://user-images.githubusercontent.com/82653875/120196269-b5d84380-c230-11eb-82b8-10f33a4d56c1.jpg)
I think so. The `html-form` of the site tells you what you can upload and in what formats. Using the `requests` library in Python, we can write a request to upload images to this service.
This repository is entirely dedicated to working with the Web Services API, perhaps. In the future, I will develop similar applications, but I can't say exactly when.
